docs/getting-started.md

I think there is a missing `cd` in the tutorial, so this PR adds the cd

add documentation for cd to the piko dir

---

cli/agent/command.go
cli/command.go
cli/server/command.go

Improves the CLI help message for commands `piko`, `piko server` and `piko agent`

cli: extend docs

---

Makefile
docs/manage/kubernetes.md
operations/helm/piko/Chart.yaml
operations/helm/piko/templates/_helpers.tpl
operations/helm/piko/templates/configmap.yaml
operations/helm/piko/templates/service.yaml
operations/helm/piko/templates/serviceaccount.yaml
operations/helm/piko/templates/statefulset.yaml
operations/helm/piko/values.yaml
server/server/admin/server.go

Fixes https://github.com/andydunstall/piko/issues/22
Adds a simple Helm chart that creates a headless service and statefulset of Piko nodes. Piko uses the headless service domain to resolve the other pods in the cluster. (Just trying to get started with a simple chart that can be extended later)

helm: add piko helm chart

---

agent/forwarder.go
cli/workload/requests.go
workload/config/requests.go

When the HTTP response body is copied, it seems to sometimes fail due to the request context being cancelled. As a temporary workaround, this copies the response body before the context is cancelled.

fix: forwarder copy body eof

---

client/client.go
client/client_test.go
client/listener.go
client/options.go

Adds a basic interface for the Piko Go client. The client is not yet functional.

client: add go sdk interface

---

agentv2/config/config.go
agentv2/config/config_test.go
cli/agentv2/command.go
cli/agentv2/http.go
cli/agentv2/ping.go
cli/agentv2/start.go
cli/command.go
client/client.go
client/client_test.go
client/options.go

Adds the CLI and configuration for the new agent command line tool. This is not yet functional so is hidden from 'piko -h'.

agentv2: add agent cli and configuration

---

agentv2/config/config.go
agentv2/endpoint/endpoint.go
cli/agentv2/http.go
cli/agentv2/start.go

Adds an 'agent.Endpoint' interface that accepts a Piko listener. The endpoint can then run a reverse proxy to forward requests to the upstream.
Updates the agent command to open a connection to the server, register each endpoint and start the endpoint.

agentv2: add endpoint interface

---

agentv2/config/config.go
agentv2/config/config_test.go
agentv2/endpoint/endpoint.go
agentv2/endpoint/endpoint_integration_test.go

Adds a simple reverse proxy to the agent 'Endpoint', which listens for connections on the Piko listener and forwards to the upstream.

agentv2: add endpoint reverse proxy

---

agent/config/config.go
agent/endpoint.go
cli/agent/command.go
docs/manage/configure.md
pkg/conn/websocket/websocket.go
pkg/testutil/tls.go
server/config/config.go
server/config/proxy.go
server/config/tls.go
server/server.go
server/server/admin/server.go
server/server/admin/server_integration_test.go
server/server/proxy/server.go
server/server/proxy/server_integration_test.go
server/server/upstream/server.go
server/server/upstream/server_integration_test.go
tests/proxy_test.go
workload/upstream/upstream.go

Adds TLS support to both the Piko server and agent.
Each port on the server has independent TLS configuration, where TLS can be enabled and the key/cert configured.
The agent has configuration for configuring the root CA cert (which overrides using the hosts root CA).
See discussion https://github.com/andydunstall/piko/discussions/51 for context.

tls: add tls support

---

cli/agentv2/command.go
cli/agentv2/http.go
cli/agentv2/start.go
cli/command.go
cli/serverv2/command.go
client/client.go
go.mod
go.sum
pkg/websocket/conn.go
serverv2/server/upstream/server.go

agentv2: add heartbeats

---

cli/serverv2/command.go
client/client.go
client/listener.go
pkg/protocol/message.go
serverv2/server/proxy/server.go
serverv2/server/upstream/server.go
serverv2/upstream/manager.go
serverv2/upstream/upstream.go

Adds a simple serverv2 proof of concept. The server runs a HTTP reverse proxy, and to dial an upstream it looks for an existing upstream muxado connection, then creates a new stream on that existing connection.

serverv2: add reverse proxy to forward requests to upstream

---

agentv2/endpoint/logger.go
serverv2/reverseproxy/reverseproxy.go
serverv2/reverseproxy/reverseproxy_test.go
serverv2/reverseproxy/server.go
serverv2/upstream/manager.go
serverv2/upstream/server.go
serverv2/upstream/upstream.go

Instead of using httputil.ReverseProxy which has limitations around selecting which upstream to connect to, adds a custom reverse proxy.

serverv2: rewrite reverse proxy

---

serverv2/upstream/manager.go
serverv2/upstream/manager_test.go

Load balances incoming proxy requests among connected upstreams in a round-robin fashion.

serverv2: load balance among connected upstreams

---

cli/server/command.go
cli/server/status/command.go
server/admin/reverseproxy.go
server/admin/server.go
server/admin/server_test.go
server/status/client/client.go
server/status/config/config.go

Adds support for forwarding requests to the admin API to other nodes in the cluster by node ID.
This can be useful when the cluster is hosted behind a load balancer and you want to inspect a particular node by node ID.

admin: add request forwarding

---

cli/server/command.go
cli/server/status/command.go
cli/server/status/upstream.go
server/status/client/upstream.go
server/upstream/manager.go
server/upstream/status.go

Adds 'piko server status upstream endpoints' command to list the number of connected upstreams for each endpoint.

status: add upstream endpoints status command

---

agent/config/config.go
agent/reverseproxy/server.go
agent/tcpproxy/server.go
cli/agent/command.go
cli/agent/tcp.go
pkg/middleware/logger.go

Adds support for listening for raw TCP traffic on the agent.
Also adds a new 'piko agent tcp' command to create a single TCP listener.

agent: add tcp listener support

---

server/proxy/httpproxy.go
server/proxy/httpproxy_test.go
server/proxy/server.go
server/proxy/tcpproxy.go
server/proxy/tcpproxy_test.go
server/upstream/manager_test.go
server/upstream/upstream.go
tests/cluster_test.go

Adds support for forwarding a TCP port forwarding connection to another node in the cluster. This forwards the connection via the HTTP reverse proxy as it uses WebSockets as the underlying connection.

server: support clustering with tcp port forwarding

---

cli/command.go
cli/forward/command.go
cli/forward/start.go
cli/forward/tcp.go
forward/config/config.go
forward/forwarder.go

'piko forward' listens on a local TCP port then forwards incoming traffic to a configured upstream endpoint.

forward: add 'piko forward' command

---

cli/workload/upstreams.go
workload/config/upstreams.go
workload/upstream/upstream.go

Adds --churn.interval and --churn.delay to configure how often each upstream should churn (disconnect and reconnect) and the delay between disconnecting and connecting.

workload: add upstream churn

---

agent/config/config.go
cli/agent/command.go
cli/forward/command.go
cli/server/command.go
cli/workload/requests.go
cli/workload/upstreams.go
forward/config/config.go
pkg/gossip/config.go
pkg/log/config.go
server/auth/config.go
server/config/config.go
server/config/tls.go
workload/config/requests.go
workload/config/upstreams.go

Adds 'config.Default()' to set default configuration rather than adding defaults to cobra flags.

config: add config defaults

---

cli/server/command.go
server/config/config.go
server/server.go
workload/cluster/nodev2.go

Updates the server to infer the advertise address from the address being listened on rather than the configured bind address.
This means you can configure port '0' to assign a system port, then the advertise address is infered from the assigned port.

server: infer advertise address from listen address

---

forward/config/config.go

Adds missing default value to 'piko forward' CLI.

forward: fix forward configuration

---

agent/config/config_test.go
forward/config/config_test.go
server/config/config_test.go

Adds unit tests to verify the server, agent for forward default configuration is valid.

config: test default config is valid

---

cli/server/command.go
server/admin/server.go
server/admin/server_test.go
server/config/config.go
server/gossip/gossip.go
server/server.go
server/usage/reporter.go
tests/admin_test.go
workloadv2/cluster/node.go

Rather than start/stop all background goroutines at once, adds an ordering for more graceful startup and shutdown.

server: order server statup and shutdown

---

client/listener.go
client/upstream.go
go.mod
go.sum
server/upstream/server.go
server/upstream/upstream.go

This is a temporary fork to tag the latest version, rather than depend on an arbitrary commit.

yamux: updates yamux dependency to github.com/andydunstall/yamux

---

cli/command.go

Adds a -v/--version flag to Piko to display the version.

cli: add piko version

---

docs/server/server.md
pikotest/cluster/node.go
pkg/config/load_test.go
server/auth/config.go
server/config/config.go
server/config/config_test.go
server/server.go
tests/server/upstream_test.go

server: move auth to upstream config

---

docs/server/server.md
pikotest/cluster/node.go
server/admin/server.go
server/admin/server_test.go
server/config/config.go
server/config/config_test.go
server/server.go
server/upstream/server_test.go
tests/server/admin_test.go

Adds 'config.admin.auth' to configure JWT configuration for admin endpoints.

server: add support for admin authentication

---

cli/forward/command.go
client/dialer.go
forward/config/config.go

Adds a '--connect.token' option to 'piko forward' to authenticate client connections.

forward: add client authentication

---

docs/server/server.md
pikotest/cluster/node.go
pkg/gossip/config.go
server/config/config.go
server/config/config_test.go
server/server.go

Moves 'gossip' config to 'cluster.gossip', since gossip is part of the cluster configuration.

gossip: move gossip config under cluster

---

agent/tcpproxy/server.go
client/forwarder.go
forward/forwarder.go
server/proxy/tcpproxy.go

Adds debug logs when io.Copy returns an error when forwarding traffic
between two TCP connections.

tcp: add copy closed logs

---

cli/test/cluster/command.go
cli/test/workload/upstreams/command.go

Just two command-line examples

cli: fix command line examples

---

server/config/config.go

The proxy timeout should be optional.
See https://github.com/andydunstall/piko/issues/147.

server: remove proxy timeout validation

---

agent/reverseproxy/reverseproxy.go
server/proxy/httpproxy.go

Updates the HTTP proxy (both server and agent) to only apply the timeout to non-websocket requests.
This is a fairly quick fix to ensure long lived TCP and WebSocket connections work. In the future will try and apply the timeout based on the initial request response (i.e. if the request has been hijacked don't apply a timeout) instead of request header.
Fixes https://github.com/andydunstall/piko/issues/147.

proxy: only apply proxy timeout to non-websocket requests

---

agent/config/config.go

I'm getting started with Piko and tried to configure a TCP Listener in the configuration file.
```
listeners:
- endpoint_id: my-ssh
addr: '22'
protocol: tcp
timeout: 15s
```
This returns an error `config: listener: my-ssh: unsupported protocol`.
When trying with `protocol: TCP` (or even `protocol: asdf`), it continues loading, the upstream is created but I was unable to connect. It looks like the TCP configuration was not loaded correctly.

tcp: Fix protocol configuration loading

---

agent/config/config.go
cli/agent/command.go

Fixes https://github.com/andydunstall/piko/issues/160

agent: disable metrics server by default

---

go.mod
go.sum

Updates yamux to v1.5.0 which fixes yamux incorrectly returning ErrSessionShutdown when actually a retryable error occured (fixed by @moredure)

agent: update yamux to v1.5.0

---

cli/agent/command.go

Fixes https://github.com/andydunstall/piko/issues/181
`conf.Listeners[i]` isn't a pointer, so setting the default to HTTP didn't work. Also adds a `panic` to verify the agent always have the configured listeners

agent: fix default protocol

---

agent/config/config.go
forward/config/config.go

Add `tls.insecure-skip-verify` to agent and forward when connecting to the Piko server

agent: add insecure skip verify

---

agent/config/config.go
agent/config/config_test.go
agent/reverseproxy/reverseproxy.go
forward/config/config.go

Fixes https://github.com/andydunstall/piko/issues/185
Adds TLS client configuration to agent listener configuration

agent: add listener tls client config

---

agent/config/config.go
forward/config/config.go
pikotest/cluster/node.go
server/config/config_test.go
server/config/tls.go

Removes the redundant 'tls.enabled' configuration, as it can be inferred from whether the cert/key are given.

server: remove tls config enabled

---

agent/config/config.go
forward/config/config.go
server/config/tls.go

Fixes https://github.com/andydunstall/piko/issues/191.
Adds support for mTLS:
- The agent and forwarder can configure `--connect.tls.cert` and `--connect.tls.key` to present a client certificate to the server
- The server can configure `--{prefix}.tls.client-cas` to require and verify client certificates

tls: add mutual tls support

---

pkg/auth/config.go
pkg/auth/jwtverifier.go
pkg/auth/jwtverifier_test.go

Adds support for disabling disconnecting the client when their JWT expires.
See https://github.com/andydunstall/piko/issues/179#issuecomment-2532299219.
cc @dipack95

auth: add disable disconnect on expiry config

---

pkg/auth/config.go

As it stands, the flag is currently available on the JSON parser, but neither of the config options work. I noticed we were missing the `yaml` tag for the new property, which now allows for the config to be properly parsed
server.json:
```json
{
"proxy": {
"bind_addr": ":7200",
"access_log": true
},
"upstream": {
"bind_addr": ":7300",
"auth": {
"disable_disconnect_on_expiry": true
}
},
"admin": {
"bind_addr": ":7400"
},
"cluster": {
"gossip": {
"bind_addr": ":7500"
}
},
"log": {
"level": "info"
}
}
```
server.yaml
```yaml
proxy:
bind_addr: ":7200"
access_log: true
upstream:
bind_addr: ":7300"
auth:
disable_disconnect_on_expiry: true
admin:
bind_addr: ":7400"
cluster:
node_id_prefix: "sombra-proxy"
gossip:
bind_addr: ":7500"
log:
level: info
```
Errors:
```bash
$ ./piko server start …
```

server: add missing disable disconnect on expiry yaml tag

---

agent/reverseproxy/metrics.go
agent/reverseproxy/server.go
cli/agent/command.go

Fixes #216, where if the agent runs multiple endpoints, it attempts to register the same metrics multiple times so panics.
This extends the proxy metrics to include an `endpoint` label, such as:
```
piko_agent_requests_total{endpoint="endpoint1",method="GET",status="200"} 1034
piko_agent_requests_total{endpoint="endpoint2",method="GET",status="200"} 1234
```
It also registers the metrics only once to avoid panicing.
(Based on approach in #217)

agent: add per-endpoint proxy metrics

---

.github/workflows/release.yaml

Adds `package: write` permission to the release workflow to fix publishing packages to GHCR.

workflow: add package write permission to release workflow

---

agent/config/config.go
cli/agent/command.go
client/upstream.go
pkg/auth/multi_tenant_verifier.go
pkg/auth/multi_tenant_verifier_test.go
pkg/auth/verifier.go
pkg/middleware/auth.go
pkg/middleware/auth_test.go
pkg/websocket/conn.go
server/admin/server.go
server/admin/server_test.go
server/config/config.go
server/config/config_test.go
server/proxy/server.go
server/proxy/server_test.go
server/server.go
server/upstream/server.go
server/upstream/server_test.go

Fixes https://github.com/andydunstall/piko/issues/179.
Adds support for upstream multi-tenant authentication, such as:
```
upstream:
auth:
hmac_secret_key: admin-secret
tenants:
- id: tenant-1
auth:
hmac_secret_key: tenant-1-secret
- id: tenant-2
auth:
hmac_secret_key: tenant-2-secret
- id: tenant-3
auth:
hmac_secret_key: tenant-3-secret
```
This includes adding agent support for specifying a tenant ID, with `--connect.tenant-id`.

server: add upstream multi-tenant auth support

---

agent/config/config.go
agent/tcpproxy/server.go
cli/agent/http.go
cli/agent/tcp.go
pkg/log/config.go
pkg/middleware/logger.go
server/config/config.go
server/config/config_test.go

Solves https://github.com/andydunstall/piko/issues/227
I chose to only solve for the request and response header logging in this PR, as a way of proving out the concept before adding more configuration options.
- Allows for both the Agent and Proxy Server config files to specify request and response headers to allow or block
- Note only one of the properties can be specified in a configuration
- Allows for the Proxy Server, and Agent CLIs command to perform the same functionality
- The `proxy.access_log` property for the Proxy Server has been changed from a simple boolean to a more complex object, but we still retain the default option of logging all request properties, including all request and response headers

Allow for Proxy Server and Agent Access Log Config to be fine-grained.

---

client/dialer.go

Just added this to allow for websocket connections with custom server cert (or other TLS config).
I maybe wrong but it feels like it's fixing a bug (disregarding the TLSConfig struct).
Tested manually.

Support the TLS config for the agent client
