monitoring/dashboards/proxy.json, server/server.go, server/server/admin/server.go, server/server/middleware/metrics.go, server/server/proxy/server.go, server/server/upstream/server.go, server/server/upstream/server_integration_test.go
Adds HTTP request metrics for count, in-flight, latency, request size and response size.
=> server: extend http metrics

cli/workload/requests.go, server/server/admin/server.go
Registers /debug/pprof endpoints on the admin server.
=> admin: add pprof endpoints

README.md, go.mod, go.sum, server/config/config.go, server/proxy/proxy.go, server/server.go, server/usage/reporter.go
=> server: add usage reporting

docs/demo/docker-compose.yaml, docs/getting-started.md, operations/helm/piko/Chart.yaml, operations/helm/piko/values.yaml
=> add docker package

agentv2/endpoint/endpoint_integration_test.go, tests/proxy_test.go
Updates integration and system tests that rely on a running upstream server to use httptest.Server.
=> tests: use httptest.Server

agentv2/config/config.go, agentv2/endpoint/endpoint.go, agentv2/endpoint/handler.go, agentv2/endpoint/logger.go, cli/agentv2/http.go, pkg/mux/session.go, serverv2/reverseproxy/reverseproxy.go, serverv2/reverseproxy/server.go
Extends agentv2 configuration to include TLS configuration and access log.
=> agentv2: add config options

server/cluster/state.go, server/cluster/state_test.go, tests/cluster/cluster.go, tests/cluster/node.go, tests/cluster/options.go, tests/cluster_test.go, tests/node/node.go, tests/proxy_test.go
=> tests: add cluster system test

agent/client/client.go, agent/client/listener.go, agent/client/options.go, cli/agent/command.go, pkg/websocket/conn.go, server/proxy/httpproxy.go, server/proxy/httpproxy_test.go, server/proxy/server.go, server/proxy/tcpproxy.go, server/proxy/tcpproxy_test.go, tests/cluster_test.go, tests/proxy_test.go, workload/upstream/upstream.go
=> add single node port forwarding

agent/client/client.go, agent/client/listener.go
Adds 'client.ListenAndForward' to forward incoming connections from Piko to a configured address.
=> client: add listen and forward

cli/workload/requests.go, pkg/middleware/logger.go, tests/proxy_test.go, workload/upstream/upstream.go
=> workload: extend workload tooling

pkg/websocket/conn.go, server/upstream/server_test.go, tests/auth_test.go, tests/cluster/node.go, tests/cluster/options.go
=> add auth system tests

cli/server/command.go, server/config/config.go, server/proxy/server.go, server/server.go, tests/auth_test.go, tests/proxy_test.go, workload/cluster/node.go, workload/cluster/nodev2.go, workload/cluster/options.go
=> refactor server startup

server/server.go
Fixes propagating the advertise address to the rest of the cluster, by infering the advertise address before configuring the cluster state.
=> server: fix cluster state advertise addr

pkg/gossip/listener.go, pkg/gossip/protocol.go, pkg/gossip/protocol_test.go
Fixes a bug where deltas containing entries for multiple nodes can be considered as coming from a single node.
=> gossip: fix delta encoding

server/upstream/server.go, server/upstream/server_test.go, workloadv2/cluster/manager.go
=> server: disconnect upstream on shutdown

.github/workflows/build.yaml, CONTRIBUTING.md, Makefile, pkg/gossip/gossip_test.go, tests/client/upstream_test.go, tests/server/admin_test.go, tests/server/cluster_test.go, tests/server/proxy_test.go, tests/server/upstream_test.go
=> tests: organize system tests

.github/workflows/build.yaml, cli/agent/command.go, cli/forward/command.go, cli/server/command.go, cli/test/cluster/command.go, cli/test/workload/traffic/command.go, cli/test/workload/upstreams/command.go, pkg/config/config.go, pkg/config/load.go, pkg/config/load_test.go, server/config/config_test.go, tests/server/cli_test.go
=> server: config testing

docs/server/server.md, pikotest/cluster/node.go, pkg/auth/verifier.go, server/config/config.go, server/config/config_test.go, server/proxy/httpproxy.go, server/proxy/server.go, server/proxy/server_test.go, server/server.go, server/upstream/server.go, server/upstream/server_test.go, tests/server/admin_test.go, tests/server/proxy_test.go
=> add proxy auth

agent/tcpproxy/server.go, client/forwarder.go, forward/forwarder.go, server/proxy/tcpproxy.go
Replace the `nolint` with blank identifiers.
=> chore: remove nolint from source code and replace with blank identifiers

client/listener.go, client/upstream.go, go.mod, go.sum
Also updates yamux to avoid logging retryable errors as error logs within yamux.
=> client: update retryable connection error logs to warning

pkg/gossip/gossip.go, pkg/gossip/listener.go, pkg/gossip/metrics.go, pkg/gossip/state.go
Adds gossip metrics for incoming/outgoing digest and delta entries.
=> gossip: add digest/delta metrics

pkg/middleware/auth.go, pkg/middleware/auth_test.go
Fixes https://github.com/andydunstall/piko/issues/180
=> server: support x-piko-authorization header

.github/workflows/release.yaml
* Adds steps in Github actions necessary to update the `Chart.yaml` file to the new version
* Adds steps in Github actions necessary to build and publish containers to GHCR with `:latest` and `:<TAG>` (The name of the tag that triggers the action)
Closes out #199
=> feat: added container publishing and helm chart updates on tagged release

cli/server/status/cluster.go
Adds support for filtering the nodes to show in `status cluster nodes` by status with a `--status` flag.
=> status: add --status filter to cluster nodes status

cli/agent/command.go, cli/agent/http.go, cli/agent/tcp.go, pkg/log/config.go, pkg/log/logger.go, pkg/middleware/logger.go, server/config/config.go, server/config/config_test.go
Adds support for configuring the access log level.
This also changes the purpose of access-log.disable to block all access logs.
=> log: add access log level
